### ISSUE TITLE
Support IP2Location LITE in IPv4 & IPv6 IP Address?

### ISSUE THREAD

**Issue by m-cameron** [ILLKX/LookingGlass-En#1]
Do you have any plan to support IP2Location LITE? They have commercial database which has more information that we can upgrade easily once you have the library integrated.

**Comment by ILLKX** [comment]
Hello. Right now I have already supported for the GEOIP information when traceroute in IPv4. But if IP2Location's GEOIP information is more accurate than ipip.net (I don't think so) and easier to display, I would consider to support IP2Location.
